### ISSUE TITLE
error in lagged data

### ISSUE THREAD

**Issue by gregbritten** [brorfred/mapps_forest#1]
Hello! There is a problem with the [lagged data](https://github.com/brorfred/mapps_forest/tree/main/indata/lagged_data). Values for ``chl`` ``sst`` ``sat_par`` are just repeated in each table. E.g. compare [here](https://github.com/brorfred/mapps_forest/blob/main/indata/lagged_data/mapps_sat_neg_01_days.csv#:~:text=7-,5.80999755859375,-2.0) and [here](https://github.com/brorfred/mapps_forest/blob/main/indata/lagged_data/mapps_sat_neg_10_days.csv#:~:text=7-,5.80999755859375,-2.0).

**Comment by brorfred** [comment]
I’ll take a look!

**Comment by brorfred** [comment]
Hm, do you have any examples of this? Here is what i get for row 1000:

[nan,
 nan,
 nan,
 nan,
 nan,
 0.0109954215586185,
 0.0109954215586185,
 0.0114651694893836,
 0.0114651694893836,
 0.0114651694893836,
 0.0114651694893836,
 0.0114651694893836,
 0.0114651694893836,
 0.0114651694893836,
 0.0114651694893836,
 0.0114651694893836,
 0.0104612981279691,
 0.0104612981279691,
 0.0112194367684423,
 0.0112194367684423,
 0.0112194367684423,
 0.011419959180057,
 0.0117251517561574,
 0.0118427111634186,
 0.0118427111634186,
 0.012106486945413,
 0.012106486945413,
 0.0125543540343642,
 0.0125543540343642]

The repeats here happens when Chl is NaN. This is the array that's averaged over:

array([       nan,        nan, 0.01613729,        nan, 0.01395292,
              nan, 0.01254807, 0.01325111, 0.01222205,        nan,
              nan, 0.01349385,        nan, 0.00845356,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan, 0.01193492,        nan, 0.01099542,
              nan,        nan,        nan,        nan,        nan,
              nan])

Note that the day of observation is at the end of the array.

**Comment by gregbritten** [comment]
I'm looking at the lagged data (not the averages). All the tables in ``indata/lagged_data/`` have identical ``sst``, ``chl``, and ``sat_par`` columns.

**Comment by gregbritten** [comment]
Just needed the raw 365 day time series
